#!/bin/sh

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2011-present Alex@ELEC (http://alexelec.in.ua)

CH_NAME="$@"
WRK_DIR="/storage/.config/puzzle/tvh"
CH_FILE="$WRK_DIR/tvh-channels.list"
CH_TRANSCODE="$WRK_DIR/tvh-transcode.list"
CH_VLCPLAY="$WRK_DIR/tvh-vlcplay.list"
IS_NAME=''
IS_VLC=''
ACE_URL=''

LOG_VLC="quiet"
LOG_FFMPEG="quiet"
STREAM_PTV="VLC"
CACHE_PTV=3
IP4_TIME=5000
ENDODE_ARG="-vf scale=-1:720"
USER_AGENT="'SmartSDK'"

CONFIG_LOG="$WRK_DIR/stream-tvh.conf"
[ -f "$CONFIG_LOG" ] && . $CONFIG_LOG

CONFIG_FILE="/storage/.cache/services/ptv.conf"
[ -f "$CONFIG_FILE" ] && . $CONFIG_FILE

play_empty (){
  echo "*** IPTV stream --- Not found URL for ---: [$CH_NAME] ***" >&2
  URL="/storage/.config/puzzle/logo/empty-stream.mp4"
  /usr/bin/ffmpeg -v quiet -hide_banner -i "$URL" -c copy -f mpegts pipe:1
  sleep 3
  exit 3
}

FIND_CH_NAME=`echo "$CH_NAME" | sed 's|\[|\\\[|g; s|\]|\\\]|g'`
URL_PTV=`grep -m 1 "^$FIND_CH_NAME #" $CH_FILE | awk -F\\# '{print $2}' | sed 's/^[ \t]*//; s/[ \t]*$//'`
[ -z "$URL_PTV" ] && play_empty

URL=`curl -s $URL_PTV`
[ -z "$URL" ] && play_empty

EMPTY_URL=`echo $URL | grep '/logo/empty-stream.mp4'`
[ -n "$EMPTY_URL" ] && play_empty

if [ ! -f "/run/lock/start.tvip" ]; then
  [ -f "$CH_TRANSCODE" ] && IS_NAME=`grep -m 1 "^$CH_NAME #" $CH_TRANSCODE | awk -F\\# '{print $1}' | sed 's/^[ \t]*//; s/[ \t]*$//'`
fi

[ "$FF_TRANSCODE" == "low" ] && ENDODE_ARG="-vf scale=iw/2:ih/2"

DUNE_URL=`echo $URL | grep 'hls.peers.tv'`
[ -n "$DUNE_URL" ] && USER_AGENT="'DuneHD/1.0.3'"

if [ "$STREAM_PTV" == "VLC" ]; then
  ACE_URL=`echo $URL | grep '/ace/getstream'`
  if [ -z "$ACE_URL" -a "$HYBRID_MODE" == "yes" ]; then
    [ -f "$CH_VLCPLAY" ] && IS_VLC=`grep -m 1 "^$CH_NAME #" $CH_VLCPLAY | awk -F\\# '{print $1}' | sed 's/^[ \t]*//; s/[ \t]*$//'`
    [ -z "$IS_VLC" ] && STREAM_PTV="FFmpeg"
  fi
fi

if [ "$STREAM_PTV" == "VLC" ]; then

  if [ "$LOG_VLC" == "info" ]; then
    DEBUG="-vvv"
  else
    DEBUG="--quiet"
  fi

  BUF_TIME=$(expr $CACHE_PTV \* 1000)

  echo "*** IPTV stream --- Real URL ---: [$URL] ***" >&2

  if [ -n "$IS_NAME" ]; then
      echo "*** IPTV stream --- VLC+Transcode --- mode: [$CH_NAME] - [$URL] (Cache time: 2 sec.)***" >&2
      /usr/bin/cvlc $DEBUG --ipv4-timeout=$IP4_TIME --network-caching=2000 \
                           --no-drop-late-frames --no-skip-frames \
                           "$URL" :http-user-agent="$USER_AGENT" \
                           --sout '#std{mux=ts,access=file,dst=-}' | \
      /usr/bin/ffmpeg -v $LOG_FFMPEG -hide_banner -i - -max_muxing_queue_size 9999 -c:v mpeg2video -q:v 3 $ENDODE_ARG -c:a copy -c:s copy -ignore_unknown -map 0 -f mpegts pipe:1
  else
      echo "*** IPTV stream --- VLC --- mode: [$CH_NAME] - [$URL] (Cache time: $CACHE_PTV sec.)***" >&2
      /usr/bin/cvlc $DEBUG --ipv4-timeout=$IP4_TIME --network-caching=$BUF_TIME \
                           --no-drop-late-frames --no-skip-frames \
                           "$URL" :http-user-agent="$USER_AGENT" \
                           --sout '#std{mux=ts,access=file,dst=-}' | \
      /usr/bin/ffmpeg -v $LOG_FFMPEG -hide_banner -i - -max_muxing_queue_size 9999 -c copy -ignore_unknown -map 0 -f mpegts pipe:1
  fi

else

  if [ -n "$IS_NAME" ]; then
      echo "*** IPTV stream --- FFmpeg+Transcode --- mode: [$CH_NAME] - [$URL] ***" >&2
      /usr/bin/ffmpeg -v $LOG_FFMPEG -hide_banner -user-agent $USER_AGENT -i "$URL" -max_muxing_queue_size 9999 -c:v mpeg2video -q:v 3 $ENDODE_ARG -c:a copy -c:s copy -ignore_unknown -map 0 -f mpegts pipe:1
  else
      echo "*** IPTV stream --- FFmpeg --- mode: [$CH_NAME] - [$URL] ***" >&2
      /usr/bin/ffmpeg -v $LOG_FFMPEG -hide_banner -user-agent $USER_AGENT -i "$URL" -max_muxing_queue_size 9999 -c copy -ignore_unknown -map 0 -f mpegts pipe:1
  fi

fi
